language: node_js
node_js:
- '0.10'
before_script:
after_script:
- npm install
- npm dedupe
- gulp build --type=prod
- uglifyjs dist/bundle.js -o dist/bundle.js --in-source-map dist/bundle.js.map --source-map dist/bundle.js.map
- surge --project ./dist --domain newui.prototypo.io
