sudo: false
language: node_js
node_js:
- '6.3'
before_install:
- npm install -g uglifyjs
after_install:
- npm dedupe
- npm shrinkwrap --dev
- cat npm-shrinkwrap.json
script:
- gulp build --type=prod
- 'surge --project ./dist --domain test.prototypo.io'
after_success:
- 'uglifyjs dist/bundle.js -o dist/bundle.js --in-source-map dist/bundle.js.map --source-map-url bundle.js.map --source-map dist/bundle.js.map'
- '[ $TRAVIS_BRANCH == master ] && surge --project ./dist --domain app.prototypo.io'
- '[ $TRAVIS_BRANCH == release ] && surge --project ./dist --domain beta.prototypo.io'
- '[ $TRAVIS_BRANCH == develop ] && surge --project ./dist --domain dev.prototypo.io'
- '[ $TRAVIS_BRANCH == feat/new-ux ] && surge --project ./dist --domain sandbox1.prototypo.io'
branches:
  only:
    - master
    - develop
    - release
    - feat/new-ux
