language: node_js
node_js:
- '0.10'
after_script:
- npm install
- npm dedupe
- gulp build
- uglifyjs dist/bundle.js -o dist/bundle.js --in-source-map dist/bundle.js.map --source-map dist/bundle.js.map
after_success:
- surge --project ./dist --domain newui.prototypo.io
